"""
Base strategy interface for LOF Backtesting Engine.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, List, Literal

import pandas as pd

from src.config import BacktestConfig


@dataclass
class Signal:
    """Trading signal generated by a strategy.
    
    Attributes:
        action: Trade direction - 'buy' or 'sell'.
        ticker: Fund ticker symbol.
        amount: Trade amount in CNY. Use float('inf') for "maximum possible".
    """
    
    action: Literal['buy', 'sell']
    ticker: str
    amount: float
    
    def __post_init__(self) -> None:
        """Validate signal parameters."""
        if self.action not in ('buy', 'sell'):
            raise ValueError(f"action must be 'buy' or 'sell', got {self.action}")
        
        if self.amount <= 0:
            raise ValueError(f"amount must be positive, got {self.amount}")


class BaseStrategy(ABC):
    """Abstract base class for trading strategies.
    
    Subclasses must implement the generate_signals method to produce
    trading signals based on market data and current positions.
    """
    
    @abstractmethod
    def generate_signals(
        self,
        row: pd.Series,
        positions: Dict[str, float],
        config: BacktestConfig
    ) -> List[Signal]:
        """Generate trading signals for the current bar.
        
        Args:
            row: Current bar data containing at minimum:
                - ticker: Fund ticker symbol
                - close: Closing price
                - nav: Net asset value
                - premium_rate: (close - nav) / nav
                - daily_limit: Maximum subscription amount (inf if unlimited)
                - volume: Trading volume
            positions: Current holdings as {ticker: shares}.
            config: Backtest configuration.
            
        Returns:
            List of Signal objects. May be empty if no action is needed.
            Signals with amount=inf indicate "use maximum possible".
        """
        pass
