"""
Base strategy interface for LOF Backtesting Engine.

LOF回测引擎基础策略接口。
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, List, Literal

import pandas as pd

from src.config import BacktestConfig


@dataclass
class Signal:
    """Trading signal generated by a strategy.

    策略生成的交易信号。

    Attributes:
        action: Trade direction - 'buy' or 'sell'. / 交易方向 - 'buy' 或 'sell'
        ticker: Fund ticker symbol. / 基金代码
        amount: Trade amount in CNY. Use float('inf') for "maximum possible". / 交易金额（人民币），使用float('inf')表示"最大可能"
    """

    action: Literal["buy", "sell"]
    ticker: str
    amount: float

    def __post_init__(self) -> None:
        """Validate signal parameters. / 验证信号参数"""
        if self.action not in ("buy", "sell"):
            raise ValueError(f"action must be 'buy' or 'sell', got {self.action}")

        if self.amount <= 0:
            raise ValueError(f"amount must be positive, got {self.amount}")


class BaseStrategy(ABC):
    """Abstract base class for trading strategies.

    Subclasses must implement the generate_signals method to produce
    trading signals based on market data and current positions.

    交易策略的抽象基类。

    子类必须实现generate_signals方法，根据市场数据和当前持仓生成交易信号。
    """

    @abstractmethod
    def generate_signals(
        self, row: pd.Series, positions: Dict[str, float], config: BacktestConfig
    ) -> List[Signal]:
        """Generate trading signals for the current bar.

        为当前K线生成交易信号。

        Args:
            row: Current bar data containing at minimum: / 当前K线数据，至少包含：
                - ticker: Fund ticker symbol / 基金代码
                - close: Closing price / 收盘价
                - nav: Net asset value / 净值
                - premium_rate: (close - nav) / nav / 溢价率
                - daily_limit: Maximum subscription amount (inf if unlimited) / 最大申购金额（无限则为inf）
                - volume: Trading volume / 成交量
            positions: Current holdings as {ticker: shares}. / 当前持仓 {基金代码: 份额}
            config: Backtest configuration. / 回测配置

        Returns:
            List of Signal objects. May be empty if no action is needed.
            Signals with amount=inf indicate "use maximum possible".

            Signal对象列表。如无需操作可为空。amount=inf的信号表示"使用最大可能金额"。
        """
        pass
